artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishanwalia30/UsefulDatasets/raw/main/FetalHealthClassification.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  required_files: ['fetal_health.csv']
  data_path: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  data_path: artifacts/data_ingestion
  train_path: artifacts/data_transformation/train.csv
  test_path: artifacts/data_transformation/test.csv