artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishanwalia30/UsefulDatasets/raw/main/FetalHealthClassification.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  required_files: ['fetal_health.csv']
  data_path: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  data_path: artifacts/data_ingestion
  train_path: artifacts/data_transformation/train.csv
  test_path: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  model_path: artifacts/model_trainer/model.pkl
  train_path: artifacts/data_transformation/train.csv

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_path: artifacts/model_trainer/model.pkl
  test_path: artifacts/data_transformation/test.csv
  metrics_file_path: metrics.yaml